name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    if: github.repository == 'aircross/baiduyunpan'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=version::${GITHUB_REF#refs/tags/}
            echo ::set-output name=ref::${GITHUB_REF#refs/tags/}
          else
            echo ::set-output name=version::snapshot
            echo ::set-output name=ref::${{ github.sha }}
          fi
          # echo ::set-output name=docker_platforms::linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          # echo ::set-output name=docker_platforms::linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm/v8,linux/arm64
          # echo ::set-output name=docker_platforms::linux/amd64
          echo ::set-output name=docker_platforms::linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm/v8,linux/arm64
          echo ::set-output name=docker_image::${{ secrets.DOCKER_USERNAME }}/baiduyunpan

          # ${{ steps.prepare.outputs.docker_platforms }}


      
      - name: Repo Tag
        working-directory: ./workdir
        id: tag
        run: |
          echo "repo_tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
          echo "release_tag=$(date +"%Y.%m.%d-%H%M%S")" >> $GITHUB_OUTPUT >> $GITHUB_OUTPUT

      
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     platforms: ${{ steps.prepare.outputs.docker_platforms }}
      #     push: true
      #     tags: "${{ steps.prepare.outputs.docker_image }}:latest"

      - name: Build docker
        id: docker
        uses: docker/build-push-action@v5
        with:
          context: ./workdir
          push: true
          file: ''
          platforms: ${{ steps.prepare.outputs.docker_platforms }}
          tags: | 
            ${{ steps.prepare.outputs.docker_image }}:latest
            ${{ steps.prepare.outputs.docker_image }}:${{ steps.tag.outputs.repo_tag }}

      # - name: Build and push docker image
      #   run: |
      #     docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
      #     --output "type=image,push=true" \
      #     --tag "${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}" \
      #     --tag "${{ steps.prepare.outputs.docker_image }}:latest" \
      #     --build-arg REF=${{ steps.prepare.outputs.ref }} \
      #     --file Dockerfile .