name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    if: github.repository == 'aircross/baiduyunpan'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=version::${GITHUB_REF#refs/tags/}
            echo ::set-output name=ref::${GITHUB_REF#refs/tags/}
          else
            echo ::set-output name=version::snapshot
            echo ::set-output name=ref::${{ github.sha }}
          fi
          # echo ::set-output name=docker_platforms::linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          # echo ::set-output name=docker_platforms::linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm/v8,linux/arm64
          echo ::set-output name=docker_platforms::linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm/v8,linux/arm64
          echo ::set-output name=docker_image::${{ secrets.DOCKER_USERNAME }}/baiduyunpan

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ steps.prepare.outputs.docker_platforms }}
          push: true
          tags: "${{ steps.prepare.outputs.docker_image }}:latest"
